# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Series' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Series
  pod 'RealmSwift'

  target 'SeriesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SeriesUITests' do
    # Pods for testing
  end

end
